name: artic-ebov
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - biopython
  - snakemake
  - samtools
  - bwa
  - goalign
  - gotree
  - muscle
  - nanopolish
  - mafft
  - iqtree
  - minimap2
  - medaka
  - racon
  - pip:
    - binlorry
#       - https://github.com/artic-network/primer-schemes/archive/v1.0.0.tar.gz
    - git+https://github.com/artic-network/fieldbioinformatics.git
    - git+https://github.com/artic-network/Porechop.git@v0.3.0pre
    - nextstrain-augur==3.0.2.dev1
